import Foundation

enum CountryFlagOverride {
    static func flagUrl(for countryName: String) -> String? {
        let flags: [String: String] = [
            "England": "https://flagcdn.com/w40/gb-eng.png",
            "Scotland": "https://flagcdn.com/w40/gb-sct.png",
            "Wales": "https://flagcdn.com/w40/gb-wls.png",
            "Germany": "https://flagcdn.com/w40/de.png",
            "Spain": "https://flagcdn.com/w40/es.png",
            "France": "https://flagcdn.com/w40/fr.png",
            "Italy": "https://flagcdn.com/w40/it.png",
            "Portugal": "https://flagcdn.com/w40/pt.png",
            "Netherlands": "https://flagcdn.com/w40/nl.png",
            "Belgium": "https://flagcdn.com/w40/be.png",
            "Croatia": "https://flagcdn.com/w40/hr.png",
            "Brazil": "https://flagcdn.com/w40/br.png",
            "Argentina": "https://flagcdn.com/w40/ar.png",
            "USA": "https://flagcdn.com/w40/us.png",
            "Mexico": "https://flagcdn.com/w40/mx.png",
            "Japan": "https://flagcdn.com/w40/jp.png",
            "South Korea": "https://flagcdn.com/w40/kr.png",
            "Australia": "https://flagcdn.com/w40/au.png",
            "Türkiye": "https://flagcdn.com/w40/tr.png",
            "Greece": "https://flagcdn.com/w40/gr.png",
            "Russia": "https://flagcdn.com/w40/ru.png",
            "Ukraine": "https://flagcdn.com/w40/ua.png",
            "Poland": "https://flagcdn.com/w40/pl.png",
            "Czechia": "https://flagcdn.com/w40/cz.png",
            "Sweden": "https://flagcdn.com/w40/se.png",
            "Norway": "https://flagcdn.com/w40/no.png",
            "Denmark": "https://flagcdn.com/w40/dk.png",
            "Switzerland": "https://flagcdn.com/w40/ch.png",
            "Austria": "https://flagcdn.com/w40/at.png",
            "Serbia": "https://flagcdn.com/w40/rs.png",
            "Hungary": "https://flagcdn.com/w40/hu.png",
            "Romania": "https://flagcdn.com/w40/ro.png",
            "Slovakia": "https://flagcdn.com/w40/sk.png",
            "Slovenia": "https://flagcdn.com/w40/si.png",
            "Bosnia & Herzegovina": "https://flagcdn.com/w40/ba.png",
            "Montenegro": "https://flagcdn.com/w40/me.png",
            "North Macedonia": "https://flagcdn.com/w40/mk.png",
            "Albania": "https://flagcdn.com/w40/al.png",
            "Morocco": "https://flagcdn.com/w40/ma.png",
            "Senegal": "https://flagcdn.com/w40/sn.png",
            "Nigeria": "https://flagcdn.com/w40/ng.png",
            "Ghana": "https://flagcdn.com/w40/gh.png",
            "Colombia": "https://flagcdn.com/w40/co.png",
            "Uruguay": "https://flagcdn.com/w40/uy.png",
            "Chile": "https://flagcdn.com/w40/cl.png",
            "Paraguay": "https://flagcdn.com/w40/py.png",
            "Ecuador": "https://flagcdn.com/w40/ec.png",
            "Peru": "https://flagcdn.com/w40/pe.png",
            "Venezuela": "https://flagcdn.com/w40/ve.png",
            "Canada": "https://flagcdn.com/w40/ca.png",
            "Kosovo": "https://flagcdn.com/w40/xk.png",
            "Equatorial Guinea": "https://flagcdn.com/w40/gq.png",
            "Côte d'Ivoire": "https://flagcdn.com/w40/ci.png",
            "Cape Verde": "https://flagcdn.com/w40/cv.png",
            "Andorra": "https://flagcdn.com/w40/ad.png",
            "Cameroon": "https://flagcdn.com/w40/cm.png",
            "Northern Ireland": "https://flagcdn.com/w40/gb-nir.png",
            "Angola": "https://flagcdn.com/w40/ao.png",
            "DR Congo": "https://flagcdn.com/w40/cd.png",
            "Dominican Republic": "https://flagcdn.com/w40/do.png",
            "Mali": "https://flagcdn.com/w40/ml.png",
            "Bulgaria": "https://flagcdn.com/w40/bg.png",
            "Estonia": "https://flagcdn.com/w40/ee.png",
            "Georgia": "https://flagcdn.com/w40/ge.png",
            "Burkina Faso": "https://flagcdn.com/w40/bf.png",
            "Lithuania": "https://flagcdn.com/w40/lt.png",
        ]
        return flags[countryName]
    }
}
